### PR TITLE
Solution for add/remove at index

### PR DESCRIPTION
**Pull request by tmartyny**
Hey @adowns01 ,

I can't make it to the whiteboard wednesdays due to childcare, but I wanted to practice with the problems. Here's a solution if it's useful for the solutions folder. I did it a little differently from the solutions already in there and included some error handling for edge cases as well.

Fun stuff, Thanks for this repo!
Teresa

### CODE REVIEW

**Comment by tmartyny** [comment]
@adowns01 I just added another one for apple stocks using a class based/OO approach with tests. If you have any feedback on ways I can improve if you want before pulling, that would be helpful.

**Comment by ameowlia** [comment]
Hi Teresa, 
Great job at writing small methods. My favorite kind of code to read is the kind that is self documenting because the methods are well named and tiny. 

Before I merge this in, can you please add links to your solutions on the problem pages? That way other people can find them easily.

Also, would you be able to make it if DBC provided childcare? We can't do anything for tomorrow, but in the future!

**Comment by tmartyny** [comment]
sure! I have a 3yo and 12yo. My daughter loves coming to dbc.

**Comment by tmartyny** [comment]
sorry, and yup, I can do that :)

**Comment by tmartyny** [comment]
done! links added to pull request.

**Pull request merged**
