### PR TITLE
Added solution to has_matching_parens

### PR DESCRIPTION
**Pull request by AmadouSallah**

### CODE REVIEW

**Comment by ameowlia** [comment]
Nice! I'll add a link to it when I add the question pages today. 

You were great last night :)

**Comment by AmadouSallah** [comment]
Hi Emelia,
Thanks. By the way, this solution is for one of the problem from last week,
not this week :).

Amadou

**Comment by ameowlia** [comment]
Fixed!

**Comment by AmadouSallah** [comment]
Thanks Amelia, you are awesome :)

Amadou

**Pull request merged**
