### PR TITLE
Add solution file and link for is_anagram question

### PR DESCRIPTION
**Pull request by kelseypedersen**
yesssssss

### CODE REVIEW

**Comment by ameowlia** [comment]
barney-confetti

**Comment by ameowlia** [comment]
eelji029x1srremie8i0

**Comment by ameowlia** [comment]
greetings

**Comment by ameowlia** [comment]
self_high_five

**Comment by ameowlia** [comment]
tumblr_m3voj5mgow1r6ni3ro2_500

**Comment by johnakers** [comment]
http://ak-hdl.buzzfed.com/static/enhanced/webdr06/2013/7/4/11/anigif_enhanced-buzz-29313-1372950034-32.gif

**Pull request merged**
