### PR TITLE
Added contact info

### PR DESCRIPTION
**Pull request by pmmenzel**

### CODE REVIEW

**Comment by ameowlia** [comment]
Would you hate me if I mentioned that you fucked up the readme styling?

**Comment by ameowlia** [comment]
:P your info is added.

**Comment by pmmenzel** [comment]
1) No, I appreciate you telling me that I fucked up the readme styling.  My bad. I pretty sure it was when I was trying to merge my local branches.  Rookie mistake..

2)  I need to update my notifications because I only saw this because I happen to check.  Otherwise, I would have fixed it immediately.   Again, my bad.

**Comment by ameowlia** [comment]
No worries. :)

**Pull request closed without merging**
